DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS business CASCADE;
DROP TABLE IF EXISTS passwords CASCADE;





CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  is_business BOOLEAN DEFAULT false,
  active BOOLEAN NOT NULL DEFAULT true,
  masterpassword VARCHAR(255) NOT NULL
);



CREATE TABLE business (
  id SERIAL PRIMARY KEY NOT NULL,
  business_name VARCHAR(255) NOT NULL,
  street VARCHAR(255) NOT NULL,
  admin_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
);


CREATE TABLE passwords (
  id SERIAL PRIMARY KEY NOT NULL,
  users_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  business_id INTEGER REFERENCES business(id) ,
  hello VARCHAR(255),
  password VARCHAR(255),
  encrypted_password VARCHAR(255)
);
